name: Build ZWSH

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libreadline-dev
      
      - name: Compile ZWSH
        run: make
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: zwsh-x86_64
          path: zwsh
